permissions:
  contents: write
on:
  push:
    branches: [ "task/investigate-release-processes" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Bump version
        id: bump_version
        uses: oflynned/android-version-bump@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app aab
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/realRelease
          signingKeyBase64: ${{ secrets.UPLOAD_KEYSTORE }}
          alias: ${{ secrets.UPLOAD_ALIAS }}
          keyStorePassword: ${{ secrets.UPLOAD_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.UPLOAD_KEY_PASSWORD }}

      - name: upload apk to Playstore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}
          packageName: com.jhb.crosswordScan
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: internal
